# ========================================================================================
#
#                                   Leve Panel
#                                 Default Config
#
# ========================================================================================

# Panel Settings
[Panel]
pos = "bottom"  # "top", "bottom", "left", "right"
layer = "bottom"  # "background", "bottom", "top", "overlay"
size = 46 # pixels
roundness = 20
margin_top = 10
margin_bottom = 10
margin_left = 25
margin_right = 25
color = "#070C1E" # Hex Color
icon_size = 32
scroll_up = "swaymsg workspace prev"
scroll_down = "swaymsg workspace next"
#exclusive_zone = 52 # reserve space, defaults to size of panel


# Widgets appear left to right
[[Left]]
widget = "menu"
exec = "griddle"
terminal = false

[[Left]]
widget = "favorite"
icon = "folder-blue.png"
exec = "pcmanfm"
terminal = false

[[Left]]
widget = "favorite"
icon = "terminal.png"
exec = "foot"
terminal = false

[[Left]]
widget = "favorite"
icon = "google-chrome.png"
exec = "google-chrome"
terminal = false


# Center Widgets
[[Center]]
widget = "desktop"
style = "dots" # "num", "numbers", "dots"


# Widgets on right side
# are added from right to left
[[Right]]
widget = "power"
exec = "wlogout"
terminal = false

[[Right]]
widget = "clock"
exec = "gsimplecal"
terminal = false

[[Right]]
widget = "volume"
exec = "pavucontrol"
terminal = false
