# ========================================================================================
#
#                            Leve Panel
#                          Default Config
#
# ========================================================================================

# Panel Settings
[Panel]
pos = "bottom"
color = "#070C1E"
size = 46
icon_size = 32
scroll_up = "swaymsg workspace prev"
scroll_down = "swaymsg workspace next"


# Widgets appear left to right
[[Left]]
widget = "menu"
exec = "griddle"
terminal = false

[[Left]]
widget = "favorite"
icon = "folder-blue.png"
exec = "pcmanfm"
terminal = false

[[Left]]
widget = "favorite"
icon = "terminal.png"
exec = "foot"
terminal = false

[[Left]]
widget = "favorite"
icon = "google-chrome.png"
exec = "google-chrome"
terminal = false


# Valid styles for desktop indicator are
# "num", "numbers", and "dots"
[[Center]]
widget = "desktop"
style = "dots"


# Widgets on right side
# are added from right to left
[[Right]]
widget = "power"
exec = "wlogout"
terminal = false

[[Right]]
widget = "clock"
exec = "gsimplecal"
terminal = false

[[Right]]
widget = "volume"
exec = "pavucontrol"
terminal = false
